# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'highline'
gem 'rake'
gem 'serverspec'

gem 'pry', '~> 0.13.1'
