AWSTemplateFormatVersion: 2010-09-09
Description: RaisetechSampleApplicationLayer
# EC2,RDS,ELB(ALB)
# Metadata:

Parameters:
  KeyPairName:
    Description: Connecting my PC to EC2 by SSH
    Type: AWS::EC2::KeyPair::KeyName
    Default: myRaiseTechEC2connectSshKey

# Mappings:

# Conditions:

Resources:
  # =============EC2インスタンス(パブリックサブネット1a)=======================================
  myRaiseTechEc2a:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairName
      # DisableApiTermination:
      ImageId: ami-082e0157fbbf13d6c
      InstanceType: t2.micro
      Monitoring: true
      SecurityGroupIds:
        - Fn::ImportValue: MyRaiseSample-it-01-SEC-myRaiseTechSecWeb01
      SubnetId:
        !ImportValue MyRaiseSample-it-01-myRaiseTechPublicSubnet01a
        # - Fn::ImportValue: MyRaiseSample-it-01-myRaiseTechPublicSubnet01a
      UserData: !Base64 |
        #!/bin/bash -ex
        # put your script here
      Tags:
        - Key: Name
          Value: MyRaiseSample-it-01-APP
# Outputs:
