AWSTemplateFormatVersion: 2010-09-09
Description: RaisetechSampleSecurityLayer
# SecurityGroup,IAM,
# Metadata:

# Parameters:

# Mappings:

# Conditions:
# ============= EC2インスタンス(Webサーバ)用SEC =======================
Resources:
  myRaiseTechSecWeb01:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # GroupName:
      GroupDescription: Allow HTTP & SSH to client host
      VpcId:
        Fn::ImportValue: MyRaiseSample-it-01-myRaiseTechVPC
      SecurityGroupIngress: # Inbound
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        # - IpProtocol: tcp
        #   FromPort: 80
        #   ToPort: 80
        #   CidrIp: ::/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      # SecurityGroupEgress: # Outbound
      #   - Security Group Rule
      Tags:
        - Key: Name
          Value: MyRaiseSample-it-01-SEC
  # ============= ELB(ALB)用SEC =======================
  myRaiseTechSecAlb01:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # GroupName:
      GroupDescription: Allow HTTP to client host
      VpcId:
        Fn::ImportValue: MyRaiseSample-it-01-myRaiseTechVPC
      SecurityGroupIngress: # Inbound
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        # - IpProtocol: tcp     ::/0はいらない?
        #   FromPort: 80
        #   ToPort: 80
        #   CidrIp: ::/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MyRaiseSample-it-01-SEC
  # ============= RDS(PostgreSQL)用SEC =======================
  myRaiseTechSecRds01:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # GroupName:
      GroupDescription: Allow PostgreSQL to EC2
      VpcId:
        Fn::ImportValue: MyRaiseSample-it-01-myRaiseTechVPC
      SecurityGroupIngress: # Inbound
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          # CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MyRaiseSample-it-01-SEC
# ============= 出力 =============================
Outputs:
  myRaiseTechSecWeb01:
    Description: SecurityGroup for WebServer
    Value: !Ref myRaiseTechSecWeb01
    Export:
      Name: !Sub "${AWS::StackName}-myRaiseTechSecWeb01"

  myRaiseTechSecRds01:
    Description: SecurityGroup for PostgreSQL
    Value: !Ref myRaiseTechSecRds01
    Export:
      Name: !Sub "${AWS::StackName}-myRaiseTechSecRds01"

  myRaiseTechSecAlb:
    Description: SecurityGroup for ALB
    Value: !Ref myRaiseTechSecAlb01
    Export:
      Name: !Sub "${AWS::StackName}-myRaiseTechSecAlb01"
