---
- hosts: MyRaiseSample-it-01-APP
  vars_files:
    - whole_vars/base_vars.yml
  roles:
    # - yum_pkg
    # - set_homebrew
    # - set_anyenv
    # - set_ruby
    - set_nodej
    - set_rails
  tasks:
    # - name: Change interpreter
    #   set_fact:
    #     ansible_python_interpreter: "/usr/bin/python"
    # - name: Install epel-release
    #   yum:
    #     name: epel-release
    #     state: present
    #   become: yes
    # - name:
    #   debug:
    #     msg: "{{ hello }}"
